/* Section 5: Introduction */
const { TextRun } = require('docx');
const L = require('./lib');
const { h1, h2, h3, p, num, numRich, bullet, bulletRich, figure, tr } = L;

module.exports = function introduction() {
  return [
    h1('5. Introduction'),

    h2('5.1 Project Briefing'),
    p('Sound Scape is a full-stack web application that brings four normally separate music experiences together in a single product: streaming recorded music on demand, discovering new music through personalised recommendation, buying physical vinyl records, and reviewing one’s own listening behaviour through analytics. The platform is built end to end in JavaScript. The client is a React 19 single-page application bundled with Vite; the server is an Express 5 REST API; and persistent data is held in a MongoDB database reached through the Mongoose object-document mapper. A catalogue of more than three thousand tracks, several hundred artists and several hundred albums was imported from the public Spotify Web API so that the artefact could be exercised against a realistic body of content rather than a handful of seed records.'),
    p('A listener arriving at Sound Scape is greeted by a cinematic landing page and can create an account, verify it through an e-mailed one-time password, and then complete a short onboarding step in which they declare the genres, moods, languages and descriptive tags they enjoy. From that point the home page is assembled for them: a personalised section is produced by matching their declared taste profile against the catalogue. They can play tracks through a persistent player, like songs, build playlists, search and filter the catalogue by category, browse and purchase vinyl editions through the Khalti payment gateway, and open an analytics dashboard that visualises the songs and genres they have been playing. A separate administrative console allows catalogue staff to manage artists, albums, songs, vinyls and lyrics, to control the visibility of catalogue entities, and to maintain the taxonomy that personalisation depends upon.'),

    h3('5.1.1 Problem Domain'),
    p('The problem domain of this project is digital music distribution and discovery. Music consumption has moved decisively to streaming, and the dominant platforms are large, closed, subscription-funded systems. Their strength is also their constraint. The recommendation engines that decide what a listener sees are proprietary, machine-learning black boxes: a listener cannot inspect why a track was suggested, and a small catalogue owner cannot reuse that engine on their own content. These platforms also draw a hard line between streaming and the physical-format economy. An artist or independent label that wants to both stream a catalogue and sell a vinyl pressing of it must operate two disconnected systems, and neither system gives the everyday listener a clear, first-person view of their own habits.'),
    p('The problem this project sets out to solve, therefore, is the absence of a lightweight, self-hostable platform that treats streaming, transparent discovery, physical-format commerce and listener analytics as one connected product over a single catalogue. Sound Scape is the technical solution to that problem. It demonstrates that a conventional web stack can host a unified catalogue, personalise discovery through an explainable rule-based recommender rather than an opaque model, attach a vinyl storefront directly to that catalogue, and return listening insight to the listener, all within one coherent application that an independent operator could realistically run.'),
    p('This project does not implement an artificial-intelligence or machine-learning component. The personalisation it provides is delivered by a deterministic, rule-based recommender that matches an explicitly declared taste profile against a structured catalogue taxonomy. Because there is no learned model, no training data and no inference engine, the AI-specific guidance in the project template, which addresses natural-language processing, computer vision, supervised or unsupervised learning, agent design, confusion matrices and ROC curves, does not apply, and those sub-sections are intentionally omitted. The decision to keep personalisation rule-based is itself a considered design position, and it is examined directly in the academic question in Section 5.5.'),

    h2('5.2 Aims'),
    p('The aim of this project is to design and develop a unified, self-hostable web platform that delivers personalised music streaming, physical-vinyl commerce and transparent listening analytics over a single catalogue, using an explainable rule-based personalisation strategy rather than an opaque machine-learning recommender.'),
    p('The aim is stated deliberately at a general level. It expresses the overall intent of the project, what the finished system is for, without describing the individual problems that must be solved to reach it. Those specific, measurable targets are set out separately as objectives in the next section.'),

    h2('5.3 Objectives'),
    p('The following objectives express the concrete problems the system is built to solve. Each was treated as a deliverable target during development and each is revisited in the Conclusion to judge whether it was met.'),
    numRich([tr('Personalise the listener’s home experience ', { bold: true }), tr('by capturing an explicit taste profile during onboarding and surfacing catalogue content, through a personalised feed, that demonstrably matches the listener’s declared genres, moods, languages and tags.')]),
    numRich([tr('Protect user accounts and sensitive actions ', { bold: true }), tr('through layered authentication: stateless JSON Web Token sessions, e-mail one-time-password verification at sign-up, third-party Google sign-in, and an OTP-gated password change that confirms the account holder before any credential is altered.')]),
    numRich([tr('Make a large imported catalogue consistently discoverable ', { bold: true }), tr('by enforcing a single shared taxonomy of genre, mood, category and language across every track, so that browsing, searching and personalisation all operate on the same reliable classification.')]),
    numRich([tr('Allow the catalogue to be monetised through physical formats ', { bold: true }), tr('by offering vinyl editions tied to albums and songs, and by completing real purchases through an integrated third-party payment gateway.')]),
    numRich([tr('Return listening insight to the listener ', { bold: true }), tr('by recording playback events and aggregating them into an analytics dashboard that reports listening hours, favourite genres and artists, activity trends and a listening streak.')]),
    numRich([tr('Keep catalogue and platform state under administrative control ', { bold: true }), tr('by providing an administrative console through which staff manage catalogue entities, govern the visibility of artists, albums and songs, and maintain the taxonomy that the rest of the system relies on.')]),

    h2('5.4 Artefact'),
    p('The artefact is the Sound Scape platform itself: a working full-stack web application comprising a React client, an Express REST API and a MongoDB database, together with the imported catalogue and the supporting administrative tooling. As a whole, the system can be understood as a layered web application. The presentation layer is a single-page React client that holds interface state in React Context stores and communicates with the server only through a dedicated API service module. The application layer is an Express REST API organised into routes, middleware and controllers, where middleware enforces authentication and authorisation and controllers hold the business logic. The data layer is a MongoDB database of thirteen Mongoose-modelled collections, supported by a static file store for audio and image media. Three external services are integrated: the Khalti payment gateway for vinyl purchases, the Spotify Web API for catalogue metadata synchronisation, and an SMTP service for transactional and one-time-password e-mail.'),
    p('To make the system tractable it was decomposed into six functional sub-systems. The Functional Decomposition Diagram in Figure 1 shows the platform broken down into those sub-systems and the principal functions each one carries out.'),
    ...figure('fig01_fdd.png', 'Functional Decomposition Diagram (FDD) of the Sound Scape platform'),
    p('The high-level architecture of the platform, its three layers and the external services it depends on, is shown in Figure 2.'),
    ...figure('fig02_architecture.png', 'Three-tier system architecture of Sound Scape'),
    p('The six sub-systems identified in the decomposition are as follows.'),
    bulletRich([tr('Authentication and Account System. ', { bold: true }), tr('Handles registration, e-mail OTP verification, login with JWT access and refresh tokens, Google OAuth sign-in, and the secure, OTP-gated password-change flow. It is the gatekeeper for every protected action in the platform.')]),
    bulletRich([tr('Music Streaming and Playback System. ', { bold: true }), tr('Handles browsing of artists, albums and songs, audio playback through a persistent player with a queue, liking of songs, creation and management of playlists, and catalogue search with category filtering.')]),
    bulletRich([tr('Personalisation and Onboarding System. ', { bold: true }), tr('Captures the listener’s taste profile during onboarding and produces the personalised feed by matching that profile against the catalogue taxonomy. It also drives mood- and genre-based discovery.')]),
    bulletRich([tr('Vinyl Store and Payment System. ', { bold: true }), tr('Presents the vinyl catalogue, renders individual vinyl pages with their tracklists, processes purchases through the Khalti payment gateway, and maintains each listener’s owned-vinyl collection.')]),
    bulletRich([tr('Admin Management System. ', { bold: true }), tr('Provides authenticated staff with create, read, update and delete control over artists, albums, songs, vinyls and lyrics, governs entity visibility, and maintains the genre, mood, category and language taxonomy.')]),
    bulletRich([tr('Analytics and Listening Data System. ', { bold: true }), tr('Records every authenticated playback event as listening history, aggregates that history into statistics, and presents it to the listener as a dashboard of animated cards and charts.')]),

    h2('5.5 Academic Question'),
    p('The academic question that this project investigates is:'),
    p('How effectively can a transparent, rule-based personalisation strategy, driven by an explicitly declared user taste profile and a unified catalogue taxonomy, support music discovery in a self-hosted streaming platform, in comparison with the opaque machine-learning recommenders used by mainstream services?', { italic: true }),
    p('The question matters because personalisation is now the defining feature of a music platform, yet on the dominant services it is delivered by collaborative-filtering and deep-learning models that are proprietary and unexplainable. Those models are powerful, but they carry well-documented costs. They require large volumes of behavioural data before they produce useful output, the so-called cold-start problem; they can narrow a listener’s exposure into a filter bubble; and crucially they cannot tell the listener why anything was recommended. For an independent catalogue owner, or for a project of academic scale, that approach is also simply unavailable: there is neither the behavioural data nor the infrastructure to train such a model.'),
    p('Sound Scape therefore takes the opposite position. Instead of inferring taste from behaviour, it asks the listener to declare it explicitly at onboarding, and it matches that declaration against a taxonomy that is enforced uniformly across the whole catalogue. The academic question asks how well that deliberately simple, fully transparent strategy actually performs as a discovery mechanism. Investigating it requires several things to be examined: whether an explicit taste profile is rich enough to produce a feed the listener finds relevant; whether a rule-based matcher can stay useful when a strict match returns too few results, which the design addresses through a tiered query that progressively relaxes its filters; whether the approach sidesteps the cold-start problem that affects behavioural models, since it needs no prior listening history; and what the strategy gives up in return, namely the serendipity and the continuous adaptation that a learned model provides. The literature review in Section 6 establishes the basis for this comparison, and the Conclusion returns to the question in the light of the completed artefact.'),

    h2('5.6 Scope and Limitations'),
    h3('5.6.1 Scope'),
    p('The following capabilities are within the scope of the delivered artefact:'),
    bullet('Account lifecycle: registration, e-mail OTP verification, JWT-based login, Google OAuth sign-in, and an OTP-gated secure password change with an e-mailed confirmation and account-recovery link.'),
    bullet('A preference-driven onboarding flow and a rule-based personalised home feed.'),
    bullet('Music browsing and playback: artist, album and song pages, a persistent audio player with a queue, liked songs, and user-created playlists.'),
    bullet('Catalogue search with a category filter, and mood- and genre-based discovery pages.'),
    bullet('A vinyl storefront with individual vinyl pages and real checkout through the Khalti payment gateway.'),
    bullet('An administrative console for managing catalogue entities, entity visibility and the catalogue taxonomy.'),
    bullet('A listening-analytics dashboard for the signed-in user, with hero statistics, charts and an activity timeline.'),
    bullet('A responsive, collapsible glassmorphism navigation shell presenting a single, consistent visual identity.'),
    h3('5.6.2 Limitations'),
    p('The following constraints bound what the artefact can do:'),
    bullet('Personalisation is rule-based and deterministic. The system does not learn from behaviour over time and does not adapt automatically; it reflects only the preferences the listener explicitly declared.'),
    bullet('The catalogue is metadata imported from the Spotify Web API. Only a subset of tracks has an uploaded, playable audio file; the remainder exist as catalogue records without streamable audio.'),
    bullet('The platform is online-only. Because data is held in MongoDB and media is served over HTTP, it cannot function without network connectivity, and no offline playback is provided.'),
    bullet('Payment integration uses the Khalti gateway, which is region-specific; the storefront therefore assumes a Nepal-based payment context.'),
    bullet('Analytics are built from playback events recorded after the feature was enabled; they cannot reconstruct earlier listening, so the dashboard becomes meaningful only as usage accumulates.'),
    bullet('The artefact is a single-operator academic deliverable. It has not been hardened or load-tested for large-scale concurrent production traffic.'),

    h2('5.7 Report Structure'),
    p('The remainder of this report is organised as follows. Section 6, the Literature Review, examines comparable platforms and relevant research on recommender systems and establishes the basis for answering the academic question. Section 7 explains the project methodology and justifies the choice of an agile, Scrum-based process. Section 8 presents the technologies and tools used and the reasons each was selected. Section 9, Artefact Designs, is the core technical section: it documents each of the six sub-systems through its requirements, its design and modelling diagrams, and its testing. Section 10 draws conclusions by returning to the aims, objectives and academic question. Section 11 is a critical evaluation of the project and includes a personal self-reflection. Section 12 presents the evidence of project management, Section 13 lists the references, and Section 14 contains the appendices.')
  ];
};
